{% set name = "xarg-python" %}
{% set version = "1.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c564d941c9b6889664d67dee4ca83589d81ce4c470516e77f5b771bbe447851b
  patches:
    - requirements.patch

build:
  entry_points:
    - xargcomplete = xarg.complete:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - argcomplete
    - pip
    - colorama
    - colorlog
    - openpyxl
    - wcwidth
    - xlrd
    - xlwt
    - tabulate
    - setuptools
    - filelock
  run:
    - filelock
    - openpyxl
    - wcwidth
    - xlrd
    - xlwt
    - tabulate
    - colorama
    - colorlog
    - python >={{ python_min }}
    - argcomplete >=3.2.1
    - tabulate

test:
  imports:
    - xarg
  commands:
    - pip check
    - xargcomplete --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bondbox/xarg-python/
  summary: Simple command-line tool based on argparse.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
