{% set name = "xarg-python" %}
{% set version = "1.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xarg-python-{{ version }}.tar.gz
  sha256: abca2e0647b7dfd599a981861dc056e022c8407b87db63f51e265a0c04618a22
  patches:
    - requirements.patch

build:
  entry_points:
    - xargcomplete = xarg.complete:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - argcomplete
    - pip
    - colorama
    - colorlog
    - openpyxl
    - wcwidth
    - xlrd
    - xlwt
    - tabulate
  run:
    - openpyxl
    - wcwidth
    - xlrd
    - xlwt
    - tabulate
    - colorama
    - colorlog
    - python >=3.8
    - argcomplete >=3.2.1
    - tabulate

test:
  imports:
    - xarg
  commands:
    - pip check
    - xargcomplete --help
  requires:
    - pip

about:
  home: https://github.com/bondbox/xarg-python/
  summary: Simple command-line tool based on argparse.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
